### ISSUE TITLE
naming of the module

### ISSUE THREAD

**Issue by cfoellmann** [OPEN-DSI/dolibarr_module_compartments#1]
I tested the module and when I put it in `htdocs/custom/compartments` it gives errors since the path is hardcoded to `htdocs/custom/compartmentstracking`.

What is the best approach?

1. adding a notice to the readme

1. changing the git repo name to `dolibarr_module_compartmentstracking`

1. changing the references to the path in the codebase from `compartments` to `compartmentstracking`

**Comment by cfoellmann** [comment]
The more I work with the code I would love if you were open to my suggestion (2).
Since the repo is fresh nearly no one will suffer renaming

**Comment by philippe-opendsi** [comment]
Hi
Renaming of the repo done
