### ISSUE TITLE
create 'develop' branch

### ISSUE THREAD

**Issue by cfoellmann** [OPEN-DSI/dolibarr_module_compartments#6]
Can you please create a `develop` branch so the `master` branch can be kept stable.
Also setting `develop` as the default branch on this page https://github.com/OPEN-DSI/dolibarr_module_compartmentstracking/settings/branches (maintainers only)

**Comment by philippe-opendsi** [comment]
Hi
Create the banch develop et send you an invite to become maintainer of this repo. Would be more simple for you :-)

**Comment by cfoellmann** [comment]
@philippe-opendsi you need to make the settings change under https://github.com/OPEN-DSI/dolibarr_module_compartmentstracking/settings/branches - no access for me (and I dont need it)
